site_name: IME Jr. - Guias do Desenvolvedor
site_url: https://ime-jr.github.io/Guias/
repo_name: ime-jr/Guias
repo_url: https://github.com/Ime-Jr/Guias
edit_uri: ''
site_description: Guias para desenvolvedores da IME Jr.
copyright: Copyright &copy; 2016 - 2024 IME Jr.

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - admonition
  - pymdownx.details

theme:
  name: material
  palette:

    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch Theme

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Dark Mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Light Mode
      
  font:
    text: Roboto
    code: Roboto Mono

  features:
  - search.suggest
  - search.highlight

  - navigation.expand
  - navigation.path
  - navigation.footer
  - navigation.tabs
  - navigation.indexes

  - content.code.annotate
  - content.code.copy
  - content.code.select
  - content.tabs.link
  - content.tooltips

nav:
  - Início: index.md
  - Matemática e Estatística:
    - Início: matematica-estatistica/inicio.md
    - Resolvendo o Campo Minado em Python: matematica-estatistica/resolvendo-o-campo-minado-com-python.md
  - Desenvolvimento Web:
    - Frontend: dolor.md
    - Backend: sit.md
  - Automação:
    - Python: amet.md
    - Shell: consectetur.md
  - Desing:
    - Figma: adipiscing.md
    - Photoshop: elit.md
  - Outros:
    - Git: adipiscing.md
    - Docker: elit.md

plugins:
  - search: null
  - git-authors:
      enabled: true
